"""added api cache

Revision ID: 58c3b6aeb29f
Revises: 4310257377bb
Create Date: 2018-04-11 09:00:56.282920

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '58c3b6aeb29f'
down_revision = '4310257377bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.Column('time', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
    sa.Column('data', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_cache_url'), 'api_cache', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_cache_url'), table_name='api_cache')
    op.drop_table('api_cache')
    # ### end Alembic commands ###
